spring:
  config:
    import: optional:credentials.yaml
  datasource:
    url: jdbc:postgresql://ep-ancient-rain-a23ruvw5.eu-central-1.aws.neon.tech/vehicle-offer-test-db?sslmode=require
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  max-http-request-header-size: 10MB

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - %msg%n"
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
teleroute:
  url: https://api.fx.demo.wktransportservices.com

kinde:
  management:
    url: ${kinde_management.url}
    client_id: ${kinde_management.client_id}
    client_secret: ${kinde_management.client_secret}
    audience: ${kinde_management.audience}
  oauth2:
    domain: ${kindeoauth.domain}
    client-id: ${kindeoauth.client_id}
    client-secret: ${kindeoauth.client_secret}
    scopes: ${kindeoauth.scopes}
    uri: ${kindeoauth.uri}

integrations:
  transeu:
    client-id: ${transeu.client_id}
    client-secret: ${transeu.client_secret}
    apikey: ${transeu.apikey}