spring:
  config:
    import: optional:credentials.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/freight
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

okta:
  oauth2:
    issuer: ${auth0.issuer}
    audience: ${auth0.audience}